<a href="https://colab.research.google.com/github/vyavasthita/dsml_learning/blob/master/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data = np.arange(1, 34, 0.5)
data

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5])

In [3]:
data.ndim

1

In [4]:
data.shape

(66,)

In [5]:
len(data)

66

In [6]:
data.reshape(22, 3)

array([[ 1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5],
       [10. , 10.5, 11. ],
       [11.5, 12. , 12.5],
       [13. , 13.5, 14. ],
       [14.5, 15. , 15.5],
       [16. , 16.5, 17. ],
       [17.5, 18. , 18.5],
       [19. , 19.5, 20. ],
       [20.5, 21. , 21.5],
       [22. , 22.5, 23. ],
       [23.5, 24. , 24.5],
       [25. , 25.5, 26. ],
       [26.5, 27. , 27.5],
       [28. , 28.5, 29. ],
       [29.5, 30. , 30.5],
       [31. , 31.5, 32. ],
       [32.5, 33. , 33.5]])

In [7]:
# A negative number means we are telling numpy to decide the row, and we will just decide the columns
data = np.arange(1, 13)
data_2 = data.reshape(-1, 4)
data_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# transpose
data_2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [9]:
data_2.T?

In [10]:
data_2.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [11]:
m1 = np.arange(1, 10).reshape(-1, 3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# indexing
print(m1[1][1])  # option 1
print(m1[1, 1])  # option 2

5
5


In [13]:
m2 = np.arange(1, 11)
# multiple indexes using list
m2[[-1, -2, -3]]

array([10,  9,  8])

In [14]:
# 2d indexing using list
m3 = np.arange(1, 10).reshape(-1, 3)
# print diagonals
print(m3[[0, 1, 2], [0, 1, 2]])

[1 5 9]


In [15]:
m3[[0, 1], [0, 1]]

array([1, 5])

In [16]:
# slicing
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
m1[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
m4 = np.arange(1, 13).reshape(-1, 4)
m4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
m4[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [20]:
m4[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [21]:
# alternative, when there is inconsistency in indexing
m4[:, [1, 3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [22]:
np.sum(m4)

np.int64(78)

In [23]:
m4
# np.min(m4, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
print(np.min(m4))

1


In [25]:
# axis - for one direction
# vertical - axis 0, horizontal - 1

In [26]:
np.min(m4, axis = 1) # min in each row

array([1, 5, 9])

In [27]:
np.min(m4, axis = 0) # min in each col

array([1, 2, 3, 4])

In [28]:
# average
np.mean(m4)

np.float64(6.5)

In [29]:
np.mean(m4, axis = 0) # in each col

array([5., 6., 7., 8.])

In [30]:
# avg between particular rows or cols

In [31]:
#sale is going on amazon
prices = np.array([50,45,25,20,35])
#your budget
budget = 30
#check if there atleast one item that sonal can purchase with budget of 30 ? => true/false
prices <= budget  # all items less than budget

array([False, False,  True,  True, False])

In [32]:
np.any(prices <= budget)  # if there is any item less than budget

np.True_

In [33]:
np.all(prices <= budget) # if all prices less than budget

np.False_

In [34]:
m5 = np.arange(1, 13).reshape(3, 4)

In [35]:
np.any(m5 > 15)

np.False_

In [36]:
np.where(m5 < 10, m5 * 0.8, m5)

array([[ 0.8,  1.6,  2.4,  3.2],
       [ 4. ,  4.8,  5.6,  6.4],
       [ 7.2, 10. , 11. , 12. ]])

In [37]:
bp = np.array([130, 150, 1110, 160, 120, 140, 170])
np.where(bp > 140, 'High BP', 'Low BP')

array(['Low BP', 'High BP', 'High BP', 'High BP', 'Low BP', 'Low BP',
       'High BP'], dtype='<U7')

In [38]:
m6 = np.array([3, 5, -1, 4, -5, 8, 2])
m6.sort() # in place
m6

array([-5, -1,  2,  3,  4,  5,  8])

In [39]:
np.sort(m6) # new sorted array

array([-5, -1,  2,  3,  4,  5,  8])

In [40]:
m7 = np.arange(1, 19).reshape(-1, 6)
m8 = np.sort(m7)[::-1]  # reverse order sorting, axis is default 1 (horizontal)
m8

array([[13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [41]:
# vertical sorting
np.sort(m8, axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [42]:
# Full sort
# Convert 2d to 1d, then sort 1d, then convert 1d to 2d again
np.sort(m7.flatten()).reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [43]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])