<a href="https://colab.research.google.com/github/vyavasthita/dsml_learning/blob/master/numpy/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [54]:
data = np.arange(1, 34, 0.5)
data

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5])

In [55]:
data.ndim

1

In [56]:
data.shape

(66,)

In [57]:
len(data)

66

In [58]:
data.reshape(22, 3)

array([[ 1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5],
       [10. , 10.5, 11. ],
       [11.5, 12. , 12.5],
       [13. , 13.5, 14. ],
       [14.5, 15. , 15.5],
       [16. , 16.5, 17. ],
       [17.5, 18. , 18.5],
       [19. , 19.5, 20. ],
       [20.5, 21. , 21.5],
       [22. , 22.5, 23. ],
       [23.5, 24. , 24.5],
       [25. , 25.5, 26. ],
       [26.5, 27. , 27.5],
       [28. , 28.5, 29. ],
       [29.5, 30. , 30.5],
       [31. , 31.5, 32. ],
       [32.5, 33. , 33.5]])

In [59]:
data.reshape(-1, 3)

array([[ 1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5],
       [10. , 10.5, 11. ],
       [11.5, 12. , 12.5],
       [13. , 13.5, 14. ],
       [14.5, 15. , 15.5],
       [16. , 16.5, 17. ],
       [17.5, 18. , 18.5],
       [19. , 19.5, 20. ],
       [20.5, 21. , 21.5],
       [22. , 22.5, 23. ],
       [23.5, 24. , 24.5],
       [25. , 25.5, 26. ],
       [26.5, 27. , 27.5],
       [28. , 28.5, 29. ],
       [29.5, 30. , 30.5],
       [31. , 31.5, 32. ],
       [32.5, 33. , 33.5]])

In [60]:
# A negative number means we are telling numpy to decide the row, and we will just decide the columns
data = np.arange(1, 13)
data_2 = data.reshape(-1, 4)
data_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
# transpose
data_2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [62]:
data_2.T?

In [63]:
data_2.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [64]:
m1 = np.arange(1, 10).reshape(-1, 3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexing

In [65]:
print(m1[1][1])  # option 1


5


In [66]:
print(m1[1, 1])  # option 2

5


In [69]:
m2 = np.arange(1, 11)
# multiple indexes using list
m2[[-1, -2, -3]]

array([10,  9,  8])

In [70]:
# 2d indexing using list
m3 = np.arange(1, 10).reshape(-1, 3)
m3
# print diagonals
print(m3[[0, 1, 2], [0, 1, 2]])

[1 5 9]


In [71]:
m3[[0, 1], [0, 1]]

array([1, 5])

In [73]:
# slicing
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
m1[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
m4 = np.arange(1, 13).reshape(-1, 4)
m4

In [75]:
m4[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [76]:
m4[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
# alternative, when there is an inconsistency in indexing
m4[:, [1, 3]]

In [ ]:
np.sum(m4)

In [ ]:
m4
# np.min(m4, axis=1)

In [ ]:
print(np.min(m4))

In [ ]:
# axis - for one direction
# vertical-axis 0, horizontal 1

In [ ]:
np.min(m4, axis = 1) # min in each row

In [ ]:
np.min(m4, axis = 0) # min in each col

In [ ]:
# average
np.mean(m4)

In [ ]:
np.mean(m4, axis = 0) # in each col

In [ ]:
# avg between particular rows or cols

In [ ]:
#sale is going on amazon
prices = np.array([50,45,25,20,35])
#your budget
budget = 30
#check if there atleast one item that sonal can purchase with budget of 30 ? => true/false
prices <= budget  # all items less than budget

In [ ]:
np.any(prices <= budget)  # if there is any item less than budget

In [ ]:
np.all(prices <= budget) # if all prices less than budget

In [ ]:
m5 = np.arange(1, 13).reshape(3, 4)

In [ ]:
np.any(m5 > 15)

In [ ]:
np.where(m5 < 10, m5 * 0.8, m5)

In [ ]:
bp = np.array([130, 150, 1110, 160, 120, 140, 170])
np.where(bp > 140, 'High BP', 'Low BP')

In [ ]:
m6 = np.array([3, 5, -1, 4, -5, 8, 2])
m6.sort() # in place
m6

In [ ]:
np.sort(m6) # new sorted array

In [ ]:
m7 = np.arange(1, 19).reshape(-1, 6)
m8 = np.sort(m7)[::-1]  # reverse order sorting, axis is default 1 (horizontal)
m8

In [ ]:
# vertical sorting
np.sort(m8, axis=0)

In [ ]:
# Full sort
# Convert 2d to 1d, then sort 1d, then convert 1d to 2d again
np.sort(m7.flatten()).reshape(-1, 3)

In [ ]:
x = np.ones((5,5))
x

In [ ]:
m5 = np.arange(1, 101).reshape(-1, 5)
m5

In [ ]:
m5[0][2]

In [ ]:
m5[[40, 41, 42, 43]]

In [ ]:
m6 = np.arange(11, 51).reshape(-1, 10)
m6

In [ ]:
m6[1:3, 4: 6]

In [ ]:
m6[0: 3: 2, 4: 7: 2]

In [ ]:
ages = np.array([2, 6, 8, 11, 12, 13, 15, 16, 22, 26, 37, 41, 44, 55, 77])
ages <= 12

In [ ]:
ages[ages <= 12]

In [ ]:
np.any(ages <= 1)

In [ ]:
np.all(ages <= 76)

In [ ]:
np.where(ages <= 35, "Young", "Old")