<a href="https://colab.research.google.com/github/vyavasthita/dsml_learning/blob/master/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
data = np.array([2, 4, 6, 8])
data

array([2, 4, 6, 8])

In [ ]:
data**2

array([ 4, 16, 36, 64])

In [ ]:
data = [item for item in range(1000000)]
data

In [ ]:
%timeit [i**2 for i in data]

114 ms ± 40.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
data2 = np.array([item for item in range(1000000)])

In [ ]:
%timeit data2**2

982 µs ± 259 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
data2.ndim

1

In [ ]:
data3 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
data3.shape

(2, 3)

In [ ]:
data4 = np.array([1, 2.5, "Raja"])

In [ ]:
data4

array(['1', '2.5', 'Raja'], dtype='<U32')

In [ ]:
data4 = np.array([1, 2.5], dtype='int')
data4

array([1, 2])

In [ ]:
data4

array([1, 2])

In [ ]:
data = np.array([1, 2, 3, 4.4], dtype='float')
data

array([1. , 2. , 3. , 4.4])

In [ ]:
res = data.astype('str')
res

array(['1.0', '2.0', '3.0', '4.4'], dtype='<U32')

In [ ]:
m1 = np.arange(33, 99, 9)
m1

array([33, 42, 51, 60, 69, 78, 87, 96])

In [ ]:
m1[[4, 5]]

array([69, 78])

In [ ]:
m1.shape

(8,)

In [ ]:
m2 = np.arange(1, 101)
m3 = m2.reshape(25, 4)
m3.ndim

2

In [ ]:
m3.shape

(25, 4)